Clarify steps for publishing a custom viz
newrelic/developer-website pull request #1180
Opened 2021-03-16 23:02 UTC by ckbrehm-github

## Description
When you serve a nerdpack locally for a custom visualization, you can see it right away in the Custom Visualization app (Apps > custom visualizations).  When you officially publish and deploy the custom viz app you have to first subscribe to the nerdpack in the NR1 catalog, log out and log back in, before the custom viz shows up in the custom visualization app.  Myself and other colleagues overlooked this step because when you're testing, you become used to just going straight to the custom visualizations app and having to subscribe to the nerdpack first (after publish and deploy) is no longer intuitive.

## Use `chore`

* for minor changes / additions / corrections to content.
* for minor changes / additions / corrections to images.
* for minor non-functional changes / additions to github actions, github templates, package or config updates, etc

```bash
git commit -m "chore: clarify steps to access published custom visualization"
```

2021-03-16 23:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/developer-website?pullRequest=1180) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/developer-website?pullRequest=1180) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/developer-website?pullRequest=1180) it.</sub>

2021-03-16 23:24 UTC, JuliaNocera requested changes
Hi there @ckbrehm-github! 

The behavior you're describing sounds like a bug to me, you shouldn't have to log out and back in before the app shows up after subscribing. We are aware of an issue which is causing folks to hard refresh the browser so this might be related. I will add a ticket for our team to assess this situation.

2021-03-17 00:06 UTC, JuliaNocera requested changes

2021-03-17 00:06 UTC, JuliaNocera commented on src/markdown-pages/build-apps/build-visualization.mdx
> +Open and follow the guide to [publish and deploy the Nerdpack to New Relic One and subscribe accounts to it](/build-apps/publish-deploy). Note that you must first subscribe to your new app, log out a
Can we change this to `Note that you must first subscribe to your new app before being able to view the visualization in the Custom Visualizations app itself (where you saw it running locally)`

2021-03-22 15:51 UTC, JuliaNocera commented on src/markdown-pages/build-apps/build-visualization.mdx
> +Open and follow the guide to [publish and deploy the Nerdpack to New Relic One and subscribe accounts to it](/build-apps/publish-deploy). Note that you must first subscribe to your new app, log out a
```suggestion
Open and follow the guide to [publish and deploy the Nerdpack to New Relic One and subscribe accounts to it](/build-apps/publish-deploy). Note that you must stop running the Nerdpack locally and remove the nerdpacks=local query parameter, then subscribe to your new Nerdpack before being able to view the visualization in the Custom Visualizations app (where you saw it running locally).
```

2021-03-22 15:52 UTC, JuliaNocera approved these changes

2021-04-02 17:24 UTC, jpvajda commented
@ckbrehm-github  and @JuliaNocera do you still want this content merged in? The PR is getting  a little stale. 🍞

2021-05-06 01:04 UTC, jpvajda commented
closing as this very stale and I haven't heard back on it's status. If it needs to be merged it can either be re-opened, or a new PR can be submitted.

2021-05-06 01:04 UTC, closed without merging