feat(docs): Custom viz docs
newrelic/developer-website pull request #1216
Opened 2021-04-01 20:33 UTC by alexronquillo

## Description

Start documentation for custom visualizations.

## Reviewer Notes

There are two new files and a bunch of images:

- "Introduction to custom visualizations" (**Explore docs > Custom visualizations**)
- "Configure your custom visualization" (**Explore docs > Custom visualizations > **)

These are fairly visual, so I recommend reviewing the amplify-rendered version of the pages rather than the md alone.

## Related Issue(s) / Ticket(s)

https://github.com/newrelic/developer-website/issues/1181

2021-04-02 01:56 UTC, jpvajda commented
@alexronquillo is there a reason we have this new guide located under `Explorer Docs`  and all these other custom viz guides Under Build apps? How do they differ, and if they are related can we make a new primary nav section called: "Custom Visualizations"

- https://developer.newrelic.com/build-apps/build-visualization
- https://developer.newrelic.com/build-apps/custom-visualizations-and-the-new-relic-one-sdk
- https://developer.newrelic.com/build-apps/customize-visualizations-with-configuration

I know we are making a big push for this particular product feature and perhaps it justifies a primary nav item in the dev site navigation and we can organize all of this content there.

@polfliet thoughts?


Other than this organization question the content looks great! 🚀

2021-04-02 01:56 UTC, jpvajda requested changes
see my comment on organizing these guides into a new primary nav item

2021-04-02 12:17 UTC, alexronquillo commented
@jpvajda Yes, there is a reason, but that reason is up for debate 😃 

The reason is that these aren't guides, they're documentation. Let me define my terms a bit:

- Guides: Instructional, narrative-driven content that teaches a reader the steps to do a particular thing. They're tutorials.
- Documentation: Informational content that teaches a reader _what_ something is, _why_ you would do something, etc.

There's going to be some overlap between those two, but I think that's a fine starting place. 

The problem that I see in a lot of the dev site content, particularly for New Relic One apps, is that some content exists _only_ in guides, so you have to remember what tutorial that you read to know where to find particular content. For example: if you want to learn more about advanced configurations, you have to look in the ["hello world" app guide](https://developer.newrelic.com/build-apps/build-hello-world-app#advance-configurations). This is problematic for at least two reasons:

1. Why do we have a section on _advanced_ setup in a "Hello world" guide?
2. Is this where someone would look to find that information if they've been building apps for a while? (My reasoning hinges on the answer to this being no 😄)

I think there are a few valid solutions to this kind of problem, but the best, IMO, is to pull that content into its own piece that focuses on advanced configuration. So then the question is: do we make that content piece a guide or documentation?

Similar to how we have a documentation piece, called [Intro to NerdStorage](https://developer.newrelic.com/explore-docs/nerdstorage) that isn't guide content (it's more informational, rather than instructional), I think there is a need for more strictly informational pieces that act as a solid source of truth. Once we have those, the guides can re-iterate that content or just link to it.

Now, back to your question, "why does _this_ content belong under _Explore docs_?" There are a few things to consider:

1. I wanted to make clear that these pieces aren't guides, they're docs. So, putting them under our docs section made sense to me.
2. @jaesius and I talked about building a "mini-site" landing page for Custom visualization content that looks like the homepage and links out to doc pieces and guide pieces. This helps solve the "where do I start?" problem and brings all the content under one roof.
3. I agree with your idea of a content/nav reorg and I think that's necessary, but that's not what this PR is about, so I tabled that for a future discussion.

Please feel free to disagree and pushback, but I think this is something worth talking through, however we end up structuring the content.

I'll also add @mmfred

2021-04-02 14:28 UTC, jpvajda approved these changes

2021-04-08 21:01 UTC, jpvajda approved these changes

2021-04-08 21:02 UTC, merged