Update to Nerdpack permissions doc
newrelic/developer-website pull request #1230
Opened 2021-04-07 20:38 UTC by zuluecho9

This is a revised PR related to the previous PR https://github.com/newrelic/developer-website/pull/1217. I had technical problems and couldn't edit it so I started over.

I think I addressed all concerns. I think it's looking better. Thank you all.

2021-04-07 23:12 UTC, jpvajda requested changes

2021-04-07 23:12 UTC, jpvajda commented on src/markdown-pages/build-apps/permission-manage-apps.mdx
> +* **Basic users** can build their own Nerdpacks locally but can't publish them or subscribe accounts to them. They can view apps and visualizations in the [apps catalog](https://opensource.newrelic.c
This reads a little odd, what can I use as a basic user?  Can we specify that?

2021-04-07 23:12 UTC, jpvajda commented on src/markdown-pages/build-apps/permission-manage-apps.mdx
> +* **Full users** can use any Nerdpacks the account they're in has been subscribed to, whether built by New Relic or by others. Full users theoretically have Nerdpack management permissions, but there
```suggestion
* **Full users** can use any subscribed Nerdpacks specific to the account they  are associated with, whether built by New Relic or by others. Full users theoretically have Nerdpack management permissions, but there may be restrictions related to custom role assignments (see below). 
```

2021-04-08 13:48 UTC, alexronquillo commented on src/markdown-pages/build-apps/permission-manage-apps.mdx
> +* **Full users** can use any Nerdpacks the account they're in has been subscribed to, whether built by New Relic or by others. Full users theoretically have Nerdpack management permissions, but there
Another suggestion:

> * **Full users** can use any Nerdpacks their accounts have subscribed to. Full users theoretically have Nerdpack management permissions, but there may be restrictions related to custom role assignments (see below).

2021-04-08 17:42 UTC, jpvajda approved these changes

2021-04-08 17:43 UTC, merged