Add fade to image gallery
newrelic/developer-website pull request #1395
Opened 2021-06-10 00:56 UTC by LizBaker

## Description

This adds a fade to the right side of the image gallery to suggest there is more to scroll. I'm not sure if we want to add animation and get rid of the fade when you reach the last image 🤷‍♀️ but here's a first pass 🎉 

## Related Issue(s) / Ticket(s)

Closes https://github.com/newrelic/developer-website/issues/1385

## Screenshot(s)
<img width="959" alt="Screen Shot 2021-06-09 at 5 51 29 PM" src="https://user-images.githubusercontent.com/39655074/121447986-a604e180-c94b-11eb-91e7-acd6a09f5eb5.png">
<img width="966" alt="Screen Shot 2021-06-09 at 5 51 41 PM" src="https://user-images.githubusercontent.com/39655074/121447993-a8ffd200-c94b-11eb-8169-0268e66a0503.png">

2021-06-10 20:57 UTC, aswanson-nr approved these changes

2021-06-10 22:41 UTC, jpvajda commented
I provided the following ux feedback to @LizBaker in slack, also adding here.

1. in Firefox, once the scroll bar disappears you can't scroll the gallery, though in chrome this isn't an issue

2. in light mode the fade is pretty intense

3.  I think each image should be clickable and open the image in a new tab so people can view it at a larger scale., --> might be a bug in css

4 I think the fade on the last image should not be present

2021-06-10 22:41 UTC, jpvajda requested changes
see my last comment for suggestions...

2021-06-14 16:05 UTC, LizBaker commented
@jpvajda fixed the click-ability issue and reduced the fade. I couldn't reproduce the issue in firefox but that may be something that was fixed by fixing the click through. I also didn't come up with a good solution for getting rid of the fade at the end of the scroll so maybe we can make a separate ticket for that?

2021-06-14 16:18 UTC, jpvajda commented
@LizBaker Thanks for working on this I still feel the light-mode fade is a little `rough`, but I know CSS can take hours to get something like this right. 🤣  

Why don't we merge this in and I'll file a Nit to make the fade better on light mode, and also try to remove the fade on the last image.

2021-06-14 20:00 UTC, aswanson-nr approved these changes

2021-06-15 16:19 UTC, merged