chore: Updated 'artifact' term for 'nerdpack items'
newrelic/developer-website pull request #1498
Opened 2021-07-28 13:27 UTC by mehreentahir16

## Description

This pull request is meant to update dev site guides to replace 'artifact' term for 'nerdpack items'

## Reviewer Notes

I've updated 'artifact' terms in all files including amplify.yml (Line 17) but I have my concerns regarding that. Please review that once.

## Related Ticket(s)

https://newrelic.atlassian.net/browse/DECODOCS-233?atlOrigin=eyJpIjoiYmQ4OTc2MTYyMjM3NGIzNDg1ZjU5ZWIwMjM0YzFiMGEiLCJwIjoiaiJ9

2021-07-28 13:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/developer-website?pullRequest=1498) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/developer-website?pullRequest=1498) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/developer-website?pullRequest=1498) it.</sub>

2021-07-28 14:57 UTC, alexronquillo requested changes
Great work on this, @mehreentahir16 ! It looks like you caught all the occurrences and then some. I left a few comments instructing which ones to leave as-is. Also, keep in mind "Nerdpack" should be capitalized as it's a branded term.

2021-07-28 14:57 UTC, alexronquillo commented on amplify.yml
> +  Nerdpack items:
Yep, let's focus only on the `.mdx` files which contain docs/guide content. These js files are out of scope for content changes.

2021-07-28 14:57 UTC, alexronquillo commented on plugins/gatsby-source-newrelic-sdk/src/navigationApi.js
> +// You can combine nerdpack items from different nerdpacks.
Even though these are in a js file, you can leave them because "artifacts" in this context is what we want to change.

2021-07-28 14:57 UTC, alexronquillo commented on src/markdown-pages/build-apps/permission-manage-apps.mdx
> +If you're an owner or admin user, you can perform any of the Nerdpack capabilities. You can create, serve, publish, tag, subscribe to, and use any and all nerdpack items, both Nerdlets and visualizat
"Nerdpack" should always be capitalized in public documentation.

2021-07-28 14:57 UTC, alexronquillo commented on src/markdown-pages/custom-viz/configuration-options.mdx
> +- `schemaType`: Nerdpack nerdpack items all have `nr1.json` metadata files. The `schemaType` describes the nerdpack item's schema. For all visualizations, `schemaType` is `VISUALIZATION`.
There are a few things I'd like to point out here:

- "Nerdpack" should always be capitalized in public documentation. 
- In the first sentence, you now have "Nerdpack nerdpack items". Let's change that to "Nerdpack items"
- In the second sentence, you can be less verbose. I recommend:

> - `schemaType`: Nerdpack items all have `nr1.json` metadata files. The `schemaType` describes the item's schema. For all visualizations, `schemaType` is `VISUALIZATION`.

2021-07-28 14:57 UTC, alexronquillo commented on src/markdown-pages/explore-docs/custom-viz.mdx
> +Because custom visualizations are nerdpack items, you publish and subscribe to them the same way you [publish and subscribe to New Relic One applications](/build-apps/publish-deploy). Once you've don
"Nerdpack" should always be capitalized in public documentation.

2021-07-28 14:57 UTC, alexronquillo commented on src/markdown-pages/explore-docs/custom-viz.mdx
> +Because custom visualizations are nerdpack items, you publish and subscribe to them the same way you [publish and subscribe to New Relic One applications](/build-apps/publish-deploy). Once you've don
I'll stop leaving this comment, but it applies to all of these :)

2021-07-28 19:39 UTC, jaesius commented
> Great work on this, @mehreentahir16 ! It looks like you caught all the occurrences and then some. I left a few comments instructing which ones to leave as-is. Also, keep in mind "Nerdpack" should be capitalized as it's a branded term.

We could have been a bit more clear in the files that needed to be changed. Learning moment for us also.

2021-07-29 11:43 UTC, alexronquillo approved these changes

2021-07-29 11:43 UTC, merged