chore: move install button to the pagetools section
newrelic/developer-website pull request #1569
Opened 2021-08-31 14:08 UTC by rudouglas

2021-08-31 14:09 UTC, rudouglas commented
<img width="1724" alt="Screenshot 2021-08-31 at 15 07 20" src="https://user-images.githubusercontent.com/17122543/131517679-1a637505-c227-481f-8e21-56f80fd29b66.png">

2021-08-31 14:47 UTC, jpvajda requested changes

2021-08-31 14:47 UTC, jpvajda commented on src/templates/QuickstartDetails.js
> +                <InstallButton quickstart={pack} onClick={handleInstallClick} />
These buttons look really far apart in the screenshots, can you look at the spacing we use on the Docs Site and adjust the margin v between the buttons so they are tighter? 

https://docs.newrelic.com/docs/using-new-relic/welcome-new-relic/get-started/find-help-use-support-portal/

2021-08-31 14:49 UTC, jpvajda commented
Are you also adding in the + icon from the feather library in this PR? See my comment on the issue, we do need that `+` icon

2021-09-03 16:23 UTC, rudouglas commented
changes completed

2021-09-03 20:10 UTC, aswanson-nr approved these changes

2021-09-03 20:41 UTC, merged

2021-09-03 20:43 UTC, zstix commented
Ugh 🤦  I caught an issue with this just _after_ I merged in this PR: the icon isn't being rendered.

I'll submit a follow-up PR to address this and some other tweaks.