Update tessen naming for required format, consistency
newrelic/developer-website pull request #1623
Opened 2021-09-14 22:51 UTC by roadlittledawn

## Description

Tessen requires that event names be `camelCase` and category to be `TitleCase`. If they're not, events do not report. I confirmed that all instrumented events sent when running locally.

I also updated the event names to use one standard name. That makes it easier to query downstream when Tessen packages up events for segment and NR1.

## Additional context
We don't quite seem to stick to a standard for tessen event naming. But generally, it seems `eventName` is the more broad of the two and `category` is a specific type of said event.

Our tessen wrapper uses this signature:

```
Tessen.track(‘’eventName”, “CategoryOfThing’’, {…})
```

Which packages that into this format in segment:

```
TDEV_CategoryOfThing_eventName
```

2021-09-14 23:34 UTC, jpvajda requested changes
had one suggestion to be consistent in naming

2021-09-14 23:34 UTC, jpvajda commented on src/pages/instant-observability.js
> +      tessen.track('instantObservability', 'CatalogSearch', {
```suggestion
      tessen.track('instantObservability', 'QuickstartCatalogSearch', {
```

2021-09-15 17:15 UTC, aswanson-nr approved these changes

2021-09-15 17:18 UTC, jpvajda approved these changes

2021-09-15 17:25 UTC, merged