feat: Added guide to query alerts for quickstarts
newrelic/developer-website pull request #1761
Opened 2021-10-08 07:19 UTC by mehreentahir16

<sup> Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>

2021-10-08 16:40 UTC, alexronquillo commented
test

```
nr-book
```
								
[src/data/nav.yml](https://github.com/newrelic/developer-website/blob/322e5923eb22f187bdbac9ee5f78779c61a19c68/src/data/nav.yml#L194) (Line 194)

2021-10-08 18:16 UTC, alexronquillo requested changes
Thanks @mehreentahir16 I think this is a great start! A lot of this feedback is about whether we have the right information in the right places. The rest is about language-level details, such as preferring present tense, active voice, etc. Looking forward to seeing your next pass!

2021-10-08 18:16 UTC, alexronquillo commented on src/markdown-pages/contribute-to-quickstarts/query-alerts-for-quickstart.mdx
> +This guide teaches you to query your existing alert conditions using Nerdgraph and use the json response to populate corresponding alert files in quickstart.
You're at the end now, so you can switch to past tense:


> In this guide, you learned...

2021-10-08 18:16 UTC, alexronquillo commented on src/markdown-pages/contribute-to-quickstarts/query-alerts-for-quickstart.mdx
> +To learn more about the quickstarts and how to create one, please refer to [Build a quickstart](/contribute-to-quickstart/build-a-quickstart).
Could you make a list here?


> In this guide, you learned how to query your existing alert conditions using NerdGraph and how to use the query's JSON response to populate corresponding alert files in quickstart. Read our documentation to learn more about:
>
> - [Alerts](https://docs.newrelic.com/docs/alerts-applied-intelligence/)
> - [Building quickstarts](/contribute-to-quickstart/build-a-quickstart)

2021-10-11 17:58 UTC, mehreentahir16 commented on src/markdown-pages/contribute-to-quickstarts/query-alerts-for-quickstart.mdx
> +Use the _static-alert.yml_ file from quickstart template and start populating it using the information returned from above query.
We're assuming that user already has quickstart. If they do, then they would have covered this part already...cloning the GitHub repo, copy the template for dashboard and alerts. 

> What if the user is working with a quickstart that doesn't even have an alerts directory? etc.

The provided template for quickstart contains the directory for alerts. This assumption doesn't seem valid to me unless the narrative is to extend an already existing quickstart.

2021-10-20 12:25 UTC, merged