fix: updated terraform version information
newrelic/developer-website pull request #2123
Opened 2022-05-25 09:09 UTC by kidk

## Description

Updated the Terraform version information, so customers use the latest version.

2022-05-25 21:41 UTC, jaesius requested changes

2022-05-25 21:41 UTC, jaesius commented on src/markdown-pages/automate-workflows/get-started-terraform.mdx
>    # Require Terraform version 0.13.x (recommended)
We should change the headline as well

2022-05-30 11:28 UTC, kidk commented on src/markdown-pages/automate-workflows/get-started-terraform.mdx
>    # Require Terraform version 0.13.x (recommended)
Good catch. Updated

2022-05-31 15:12 UTC, jaesius approved these changes

2022-05-31 15:12 UTC, merged